env:
  browser: true
  es2022: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides:
  - files: ["*.ts", "*.mts", "*.cts", "*.tsx"]
    rules:
      no-undef: off
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
plugins:
  - "@typescript-eslint"
root: true
ignorePatterns:
  - "/node_modules/**"
  - "/dist/**"
  - "/coverage/**"
rules:
  # ESLINT POSSIBLE PROBLEM RULES

  array-callback-return: error
  no-await-in-loop: error
  no-constant-binary-expression: error
  no-constructor-return: error
  no-duplicate-imports: error
  no-new-native-nonconstructor: error
  no-self-compare: error
  no-template-curly-in-string: error
  no-unmodified-loop-condition: error
  no-unreachable-loop: error
  no-unused-private-class-members: error
  require-atomic-updates: error

  # ESLINT SUGGESTION RULES

  accessor-pairs: error
  block-scoped-var: error
  class-methods-use-this: error
  consistent-return: error
  default-case: error
  eqeqeq: error
  grouped-accessor-pairs: error
  logical-assignment-operators:
    - error
    - always
    - enforceForIfStatements: true
  new-cap: error
  no-bitwise: error
  no-caller: error
  no-div-regex: error
  no-else-return: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implicit-globals: error
  no-implied-eval: error
  no-iterator: error
  no-label-var: error
  no-lonely-if: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-wrappers: error
  no-proto: error
  no-return-assign: error
  no-script-url: error
  no-sequences:
    - error
    - allowInParentheses: false
  no-undef-init: error
  no-unneeded-ternary: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-warning-comments: error
  object-shorthand: error
  operator-assignment: error
  prefer-const: error
  prefer-destructuring: error
  prefer-exponentiation-operator: error
  prefer-named-capture-group: error
  prefer-numeric-literals: error
  prefer-object-has-own: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-regex-literals: error
  prefer-rest-params: error
  prefer-spread: error
  quote-props:
    - error
    - as-needed
  radix: error
  require-unicode-regexp: error
  strict: error
  symbol-description: error
  yoda:
    - error
    - never
    - exceptRange: true

  # TYPESCRIPT-ESLINT EXTENSION RULES

  default-param-last: "off"
  "@typescript-eslint/default-param-last": error
  dot-notation: "off"
  "@typescript-eslint/dot-notation":
    - error
    - allowIndexSignaturePropertyAccess: true
  no-dupe-class-members: "off"
  "@typescript-eslint/no-dupe-class-members": error
  no-invalid-this: "off"
  "@typescript-eslint/no-invalid-this": error
  no-loop-func: "off"
  "@typescript-eslint/no-loop-func": error
  no-redeclare: "off"
  "@typescript-eslint/no-redeclare":
    - error
    - builtinGlobals: true
  no-shadow: "off"
  "@typescript-eslint/no-shadow":
    - error
    - builtinGlobals: true
      hoist: all
      allow: [resolve, reject, done, cb]
  no-throw-literal: "off"
  "@typescript-eslint/no-throw-literal": error
  no-unused-expressions: "off"
  "@typescript-eslint/no-unused-expressions":
    - error
    - allowShortCircuit: true
      allowTernary: true
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": error
  no-useless-constructor: "off"
  "@typescript-eslint/no-useless-constructor": error

  # TYPESCRIPT-ESLINT SUPPORTED RULES

  "@typescript-eslint/array-type": error
  "@typescript-eslint/ban-tslint-comment": error
  "@typescript-eslint/class-literal-property-style": error
  "@typescript-eslint/consistent-generic-constructors": error
  "@typescript-eslint/consistent-indexed-object-style": error
  "@typescript-eslint/consistent-type-assertions": error
  "@typescript-eslint/consistent-type-imports": error
  "@typescript-eslint/member-ordering":
    - error
    - default:
        - signature
        - call-signature
        - [static-field, static-get, static-set]
        - static-initialization
        - static-method
        - [instance-field, instance-get, instance-set, field, get, set]
        - constructor
        - [instance-method, method]
  "@typescript-eslint/method-signature-style": error
  "@typescript-eslint/no-base-to-string": error
  "@typescript-eslint/no-confusing-non-null-assertion": error
  "@typescript-eslint/no-duplicate-enum-values": error
  "@typescript-eslint/no-dynamic-delete": error
  "@typescript-eslint/no-extraneous-class": error
  "@typescript-eslint/no-import-type-side-effects": error
  "@typescript-eslint/no-invalid-void-type": error
  "@typescript-eslint/no-meaningless-void-operator": error
  "@typescript-eslint/no-mixed-enums": error
  "@typescript-eslint/no-non-null-asserted-nullish-coalescing": error
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-redundant-type-constituents": error
  "@typescript-eslint/no-require-imports": error
  "@typescript-eslint/no-unnecessary-boolean-literal-compare": error
  "@typescript-eslint/no-unnecessary-condition": error
  "@typescript-eslint/no-unnecessary-qualifier": error
  "@typescript-eslint/no-unnecessary-type-arguments": error
  "@typescript-eslint/no-unsafe-declaration-merging": error
  "@typescript-eslint/non-nullable-type-assertion-style": error
  "@typescript-eslint/prefer-for-of": error
  "@typescript-eslint/prefer-function-type": error
  "@typescript-eslint/prefer-includes": error
  "@typescript-eslint/prefer-literal-enum-member": error
  "@typescript-eslint/prefer-nullish-coalescing": error
  "@typescript-eslint/prefer-reduce-type-parameter": error
  "@typescript-eslint/prefer-return-this-type": error
  "@typescript-eslint/prefer-string-starts-ends-with": error
  "@typescript-eslint/prefer-ts-expect-error": error
  "@typescript-eslint/promise-function-async": error
  "@typescript-eslint/require-array-sort-compare": error
  "@typescript-eslint/unified-signatures": error

  # PRETTIER COMPATIBILITY RULES

  # see https://github.com/prettier/eslint-plugin-prettier/issues/65
  arrow-body-style: "off"
  prefer-arrow-callback: "off"

  curly: error
  max-len: "off"
  no-confusing-arrow:
    - error
    - allowParens: false
  no-mixed-operators: "off"
  no-tabs:
    - error
    - allowIndentationTabs: true
  no-unexpected-mulltiline: "off"
